### ISSUE TITLE
adapt cmdchan for 9front

### ISSUE THREAD

**Issue by metacoma** [9mine/9cmdchan#1]
At this moment, we have cheap and ugly realization of cmdchan for inferno, they looks like:

```
load file2chan
load std
ndb/cs
for host_var in `{ os env } { '{'$host_var'}' }
WEBHOOK_DIR=/webhook_queue
dir = $EXPORT_PATH
port = $EXPORT_PORT
env
cmd_chan_dir = /tmp/file2chan
test -d $CMD_CHAN_DIR || mkdir -p $CMD_CHAN_DIR
output_file := /tmp/output_file
file2chan $CMD_CHAN_DIR^/cmd {
      if {~ ${rget offset} 0} {
        cat $output_file | putrdata
      } {
        rread ''
      }
    } {
      sh -c ${rget data} >$output_file >>[2]$output_file
  	}

listen -A 'tcp!*!'$port { export $dir & } &
```

example workflow: 
```
; mount -A tcp!remote!port /n/remote
; echo "echo remote namespace" >> /n/remote/tmp/file2chan/cmd
; cat /n/remote/tmp/file2chan/cmd
remote namespace 
```
this simple 9p fileserver allow you to execute commands in minetest console, pass them inside the mounted namespace, and output stdout the result back to the minetest console.

![screencast](https://user-images.githubusercontent.com/5146707/98446792-931dfa80-2139-11eb-8e22-a1e93bcae101.png)

**Bountysource**
-----------
https://www.bountysource.com/issues/94025107-adapt-cmdchan-for-9front

**Comment by ghost** [comment]
I found this from the bounty source page and might be interested in going after it. Where can I learn about cmdchan?

**Comment by metacoma** [comment]
hey @yujiri8 

cmdchan is a 9p fileserver based on sh-file2chan application.
http://man.cat-v.org/inferno/1/sh-file2chan

```file2chan $CMD_CHAN_DIR^/cmd {
      if {~ ${rget offset} 0} {
        cat $output_file | putrdata
      } {
        rread ''
      }
    } {
      sh -c ${rget data} >$output_file >>[2]$output_file
  	}

```

Are you still sure that you like this issue? :)

**Comment by okvik** [comment]
The [mq(4)](https://github.com/okvik/mq) message queue is a primitive which enables trivial implementation of 9mine 'cmdchan' abstraction.

Additionally I've provided 9front test infrastructure and verbal support for @metacoma to implement the rest of the code.
